# Generated by Django 6.0.3 on 2026-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('teleconsultation', 'Teleconsultation')], default='in_person', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
