# Generated by Django 6.0.3 on 2026-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability_slot_duration_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
    ]
