# Generated by Django 6.0.3 on 2026-05-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_is_verified_and_more'),
        ('doctors', '0004_doctorprofile_phone_number_and_more'),
    ]

    operations = [
    ]
